# Generated by Django 4.2 on 2024-02-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255)),
                ("approved", models.BooleanField(default=False, verbose_name="Paid")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.CharField(max_length=250, verbose_name="Payment Comment"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.card",
                        verbose_name="Customer Order",
                    ),
                ),
            ],
        ),
    ]
