# Generated by Django 4.2 on 2024-02-21 21:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_mediafile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="media",
            field=models.FileField(null=True, upload_to=blog.models.media_file_path),
        ),
    ]
