# Generated by Django 4.2 on 2024-02-21 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_mediafile_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videogallery",
            name="article",
        ),
        migrations.DeleteModel(
            name="ImageGallery",
        ),
        migrations.DeleteModel(
            name="VideoGallery",
        ),
    ]
