# Generated by Django 4.2 on 2024-02-22 15:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_remove_videogallery_article_delete_imagegallery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
