# Generated by Django 4.2 on 2024-02-20 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={
                "ordering": ("-created_at",),
                "verbose_name_plural": "Customer Carts",
            },
        ),
    ]
