# Generated by Django 4.2 on 2024-02-22 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_card_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carditem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
