# Generated by Django 4.2 on 2024-02-16 10:40

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_comment_product_alter_comment_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="imagegallery",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagegallery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="videogallery",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videogallery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="imagegallery",
            name="image",
            field=models.ImageField(
                null=True, upload_to=products.models.gallery_image_path
            ),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="video",
            field=models.FileField(
                null=True, upload_to=products.models.gallery_vodeo_path
            ),
        ),
    ]
